package insilico.core.alerts.builders;

/**
 *
 * @author Alberto
 */
public class SACombaseMutagenicityAccuracy {

    final static String[][] Acc = {
        {"C#N","1"},
        {"CCOC=O","1"},
        {"CCCCOCC","1"},
        {"C=CCO","1"},
        {"C(=O)(CC(C))OCC","1"},
        {"CCOC(C)=O","1"},
        {"CCCCCCO","1"},
        {"C(=O)CCCCC","1"},
        {"CC#N","1"},
        {"CCCCCCCCC","1"},
        {"CC=C(C)C","1"},
        {"Cc1ccccc1(O)","1"},
        {"CCCCCC=O","1"},
        {"O=COC(C#N)c1cccc(Oc2ccccc2)c1","1"},
        {"CCCCCCCCCC","1"},
        {"CCC=C(C)C","1"},
        {"CCCCCC(=O)O","1"},
        {"CCCCCCC(=O)O","1"},
        {"CCCCCCCCO","1"},
        {"CCCCCCCO","1"},
        {"CCCCC=C(C)C","1"},
        {"CCCCCCC=O","1"},
        {"[$(C(F)(F)F),$(C(F)(Cl)F)]","1"},
        {"C(=O)(O)CCCCCCCC","1"},
        {"CCCCCCCCCCCC","1"},
        {"c1(cc(ccc1)Cl)Cl","1"},
        {"Cc1ccc(Cl)cc1","1"},
        {"c1cc(cc(c1)Cl)Cl","1"},
        {"FC(F)F","1"},
        {"C=CC(O)=O","1"},
        {"CCCCCCCCCCC","1"},
        {"CCCCCCCCCCCC","1"},
        {"CCCCCCCCC(=O)O","1"},
        {"CCCCCCCCCO","1"},
        {"C(F)(F)C","1"},
        {"CC(CC)CCC","1"},
        {"c1(c(Cl)cccc1)C","1"},
        {"c1(CC)cc(OC)ccc1","1"},
        {"O=C(O)c1ccccc1","1"},
        {"C=C(C)C=O","1"},
        {"OCC(=O)O","1"},
        {"CCCCCCCCCC(=O)O","1"},
        {"CCCCCCCCCCO","1"},
        {"BrCC(Br)([*])[*]","1"},
        {"CC(C[O;H1;D1])[N+]([O-])=O","1"},
        {"c1ncncn1","1"},
        {"[c;R1;!R2;!R3]1[c;R1;!R2;!R3]n[c;R1;!R2;!R3]n[c;R1;!R2;!R3]1","1"},
        {"[$(C[Cl,Br]);!$(C([Cl,Br])[Cl,Br])]C#N","1"},
        {"n1c(nc(nc1))","1"},
        {"C(=O)(C(CCC(=O)O))O","1"},
        {"C(=O)(CCC(=O)O)","1"},
        {"c1(CCCCCC)ccccc1","1"},
        {"c1c(C(F)(F)F)cccc1","1"},
        {"C=CC=C(CCC)C","1"},
        {"C1CC(CC(C1))(C)C","1"},
        {"N#CCC","1"},
        {"c1(F)ccc(cc1)C","1"},
        {"C(=C(CC)C)C=O","1"},
        {"C(=O)(C)OCCCC","1"},
        {"c1(C(=O)O)c(ccc(c1))O","1"},
        {"Cc1cc(c(cc1)OC)OC","1"},
        {"C(=O)(O)Cc1ccccc1","1"},
        {"c1(cc(ccc1CCC)O)O","1"},
        {"OCCOCCO","1"},
        {"[N+]([O-])CC","1"},
        {"CC(C)=O","1"},
        {"C=CC(=O)OC","1"},
        {"C1CCCCC1","1"},
        {"CCCCCCCCCCCCC","1"},
        {"CCCCC(C)CC","1"},
        {"CCSC","1"},
        {"FC(F)(F)c1ccccc1","1"},
        {"CCCCCCCCCCCCCC","1"},
        {"CCCCCCCCCCCCCCC","1"},
        {"CCCCCCCCCCCCCCCC","1"},
        {"CCCCOC=O","1"},
        {"CCS","1"},
        {"O=C(O)CCC(=O)O","1"},
        {"CC(=C)CCC=C(C)C","1"},
        {"CCCCCCCCCCCCO","1"},
        {"CC=C(C)CCC=C(C)C","1"},
        {"CCCCCCCCCCCO","1"},
        {"O=CCCC(=O)O","1"},
        {"OC1CCCCC1","1"},
        {"Cc1ccccc1","0.93"},
        {"CCC(=O)O","0.92"},
        {"CCCC(=O)O","0.92"},
        {"CCCCC(=O)O","0.92"},
        {"CCCC(C)C","0.92"},
        {"CCCC(C)C","0.92"},
        {"c1ccc(cc1)Cl","0.91"},
        {"CCCCCC","0.91"},
        {"Oc1ccccc1","0.9"},
        {"CC(=O)O","0.89"},
        {"CCCCO","0.89"},
        {"CCCCCCC","0.89"},
        {"CCCCCCC","0.89"},
        {"CCCCCCCC","0.89"},
        {"CCOCC","0.89"},
        {"CCC","0.88"},
        {"CCCCC","0.87"},
        {"CC(C)C","0.87"},
        {"CCCC=O","0.87"},
        {"CCCC(=O)OC","0.87"},
        {"CCCC","0.86"},
        {"CCC(C)C","0.86"},
        {"CCO","0.85"},
        {"c1ccccc1","0.85"},
        {"O=CO","0.85"},
        {"C1CC1","0.85"},
        {"O=COCc1ccccc1","0.83"},
        {"CCOC","0.82"},
        {"CC=C","0.81"},
        {"CCCCN","0.75"},
        {"CCCN","0.67"},
        {"C(=O)(N(c1ccccc1))N","0.67"},
        {"CC(C)N","0.67"},
        {"CSC","0.67"},
        {"CCN","0.65"},
        {"CCNC","0.64"},
        {"c1ccncc1","0.6"},
        {"ac1cncn1","1"},
        {"C1CO1","1"},
        {"[*]Nc1ncc[n]1","1"},
        {"[C;D2](=O)C=O","1"},
        {"OC(=O)C[Br,I]","1"},
        {"OC(=O)CBr","1"},
        {"ac1nc(a)c(a)n1","1"},
        {"ac1nccn1","1"},
        {"SC(=CCl)Cl","1"},
        {"CCNCCCl","1"},
        {"C(Cl)(Cl)Cl","1"},
        {"n1c(N)n(c2ccccc12)","1"},
        {"C1OC1","1"},
        {"O=CC(=C)Cl","1"},
        {"C1CO1","1"},
        {"CCNCCCl","1"},
        {"NCCCl","1"},
        {"CNCCCl","1"}     
    };
    
    
    public static Double FindAccuracy (String SMARTS) {

        for (String[] strings : Acc) {
            String s = strings[0];
            if (s.equals(SMARTS)) {
                return Double.parseDouble(strings[1]);
            }
        }
        
        return null;
    }
    
}
